---
- name: Ping Module
  hosts: localhost
  tasks:
    - name: Using ping Module
      ansible.builtin.ping:
      register: ping

    - name: Show ping output 
      ansible.builtin.debug:
        var: ping
        #msg: "{{ ping.changed }}"

  