---
- name: Ping Module
  hosts: localhost
  tasks:
    - name: Using ping Module
      ansible.builtin.ping:
      register: ping_output

    - name: Show ping output 
      ansible.builtin.debug:
      msg: ping_output
  