---
- name: Task1
  #hosts: web
  hosts: local
  connection: local
  tasks:
   - name: Print Hello World
     ansible.builtin.debug:
        msg: "Hello World"

- name: Task2
  #hosts: web
  hosts: local
  connection: local
  tasks:
   - name: Print Task1 and Task2
     ansible.builtin.debug:
        msg: "Task1 and Task2 from mulitple plays"

